Welcome to the motherload.

this cant be blocked due to the secure github backdoor that was found

if a website is blocked then try another website, if all are blocked then message kallmefel on discord. :)

developed by exo14-2

*History Spot Alternates*

historyspot.cc
historyspot.com
historyspot.net

*Geometry Spot Alternates*

geometryspot.com
geometryspot.cc
geometryspot.net
geometryspot.school
geometryspot.ooo
geometryspot.us
https://geometryspot.de (works for securly, goguardian, and guardio)

*Random Websites*

www.sammycheez.com
https://simplecalc.com
https://coolmathgames.com
https://getting-over-it-online.github.io
https://run3.blog/













*Instruction to the motherboard*

to continue to the next step you need to prove you are worthy of the better motherload,
the motherboard.

To continue; change jekyll to exo14 in the link.
